### ISSUE TITLE
Column Classes Settings box improvements

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#11]
<img alt="widgets_ _genesis_test_site_ _wordpress" src="https://cloud.githubusercontent.com/assets/411524/14427907/1b247a44-fff7-11e5-8a46-d92eb458857d.png">
* [x] Checkbox needs to sit on top
* [x] Rest of the widget needs to be hidden is checkbox isn't checked
* [ ] Top Section (everything above) should perhaps go into a separate setting?

**Comment by ryanhellyer** [comment]
I'm not sure what this bit is referring to ... " Top Section (everything above) should perhaps go into a separate setting?"

**Comment by defries** [comment]
> I'm not sure what this bit is referring to ... " Top Section (everything above) should perhaps go into a separate setting?"

One could argue that the option to add a CSS class manually should go with the Column Class section. Yes, they both intend to add a CSS class, but the top one is (should be) on widget level and the column classes are not(?)

**Comment by ryanhellyer** [comment]
Sorry, but I'm still have trouble trying to work out what this means.
Are you perhaps saying that the number of columns should be in it's own separate section?

Although I'm not sure there is much point in having the column classes at all anymore, since we have provided a way to do that by just selecting the numbered pulldown.

**Comment by defries** [comment]
I think we can do with just the column selector for now

**Comment by ryanhellyer** [comment]
Only column selector remains in develop branch now. I think this makes sense, as the others are not useful any longer.
