### ISSUE TITLE
FontAwesome maintenance

### ISSUE THREAD

**Issue by defries** [ThemeMix/thememix-pro-genesis#17]
When I check the number of icon fonts in the widget dropdown, it doesn't appear that all the available fonts are there.

We need to two things:
* [x] Double check if they are all there and document how to make sure we have all of them available in the dropdown.
* [x] A clear description of how to update the FontAweseom assets to the latest FontAwesome version in the form of a FontAwesome.md file in the repo here.

**Comment by ryanhellyer** [comment]
The extra ones were there, but the navigations were white on a white background, and had no text or image in them :P They now use small black triangles to aid with navigating through all the Font Awesome icons.

![font-awesome-icons](https://cloud.githubusercontent.com/assets/430544/15863266/8f80cdd6-2cd2-11e6-8c0f-23ef60b8ae0b.png)

**Comment by defries** [comment]
Ah, yeah, white on white requires a special kind of smart to see ;)

**Comment by ryanhellyer** [comment]
Instructions are now in the README.md file on how to update the font icons list. Since the instructions are in there and publicly available, I made it a little simpler to regenerate them. I had previously required a require() statement to be uncommented to regenerate them. I don't think it's a good idea for random users to be updating those, so I mentioned that it's an advanced option and their changes will be wiped during the next plugin update anyway. There is intentionally no option in the UI to update the icons.
